import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/provider";
import Footer from "./components/footer/Footer";
import NewsLetter from "./components/newsLetter/NewsLetter";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <ToastContainer />
          {children}
          <NewsLetter />
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
