import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/provider";


const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
      <body className={inter.className}>
        {children}
        
      </body>
      </Providers>
    </html>
  );
}
